Server/ClassroomEvents/src/main/java/br/ufscar/dc/gsdr/ClassroomEvents/model/Room.java
package br.ufscar.dc.gsdr.ClassroomEvents.model;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Transient;

import org.codehaus.jackson.annotate.JsonIgnore;

import br.ufscar.dc.gsdr.ClassroomEvents.util.Cartesian2PointsWidhtHeightObject;
import br.ufscar.dc.gsdr.ClassroomEvents.util.Cartesian4PointsObject;
import br.ufscar.dc.gsdr.ClassroomEvents.util.CoordinatesConverter;

@Entity
public class Room implements Comparable<Room>{
	
	@Transient
	private Cartesian2PointsWidhtHeightObject c2 = null;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@Column
	private String name;
	
	@Column
	private Double xa;
	
	@Column
	private Double xb;
	
	@Column
	private Double ya;
	
	@Column
	private Double yb;
	
	public Long getLeft(){
		if(c2 == null)
			c2 = CoordinatesConverter.to2P(new Cartesian4PointsObject(xa, xb, ya, yb));
		return c2.getLeft();
	}
	
	public Long getTop(){
		if(c2 == null)
			c2 = CoordinatesConverter.to2P(new Cartesian4PointsObject(xa, xb, ya, yb));
		return c2.getTop();
	}
	
	public Long getWidth(){
		if(c2 == null)
			c2 = CoordinatesConverter.to2P(new Cartesian4PointsObject(xa, xb, ya, yb));
		return c2.getWidth();
	}
	
	public Long getHeight(){
		if(c2 == null)
			c2 = CoordinatesConverter.to2P(new Cartesian4PointsObject(xa, xb, ya, yb));
		return c2.getHeight();
	}
	
	
	@ManyToOne
	@JsonIgnore
	private Floor floor;
	
	@ManyToMany
	@JsonIgnore
	private List<Secretary> secretaries;
	
	@OneToMany(mappedBy="room")
	@JsonIgnore
	private List<Reserve> reserves;
	
	@OneToMany(mappedBy="room")
	@JsonIgnore
	private List<ResourceRoom> resourceRooms;
	
	
	public Room(){
		
	}




	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Room other = (Room) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}




	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	

	public Double getXa() {
		return xa;
	}

	public void setXa(Double xa) {
		this.xa = xa;
	}

	public Double getXb() {
		return xb;
	}

	public void setXb(Double xb) {
		this.xb = xb;
	}

	public Double getYa() {
		return ya;
	}

	public void setYa(Double ya) {
		this.ya = ya;
	}

	public Double getYb() {
		return yb;
	}

	public void setYb(Double yb) {
		this.yb = yb;
	}

	public Floor getFloor() {
		return floor;
	}

	public void setFloor(Floor floor) {
		this.floor = floor;
	}

	

	public List<Secretary> getSecretaries() {
		return secretaries;
	}

	public void setSecretaries(List<Secretary> secretaries) {
		this.secretaries = secretaries;
	}

	public Long getId() {
		return id;
	}

	public List<Reserve> getReserves() {
		return reserves;
	}

	public void setReserves(List<Reserve> reserves) {
		this.reserves = reserves;
	}

	public List<ResourceRoom> getResourceRooms() {
		return resourceRooms;
	}

	public void setResourceRooms(List<ResourceRoom> resourceRooms) {
		this.resourceRooms = resourceRooms;
	}

	@Override
	public int compareTo(Room o) {
		return id.compareTo(o.getId());
	}

	
	
	
	
}

Server/ClassroomEvents/src/main/webapp/management/room/listCreate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    template="/WEB-INF/templates/system.xhtml">
    <ui:define name="content">
<h:form id="form">
    	<div style="text-align:center;">
        	<h1>Listagem de Salas</h1>
        	<p:growl id="growl" autoUpdate="true"/>
        	<h:panelGrid columns="3">
        		<h:outputLabel value="Departamento" />
	        	<p:autoComplete value="#{roomListCreateMB.departmentSelected}" id="completeDepartment" completeMethod="#{roomListCreateMB.completeDepartment}" 
					var="dep" itemLabel="#{dep.institution.name} - #{dep.name}" itemValue="#{dep}" forceSelection="true" 
					converter="#{departmentConverter}" dropdown="true" size="70" required="true" requiredMessage="Selecione o departamento"
					>
					<p:ajax event="itemSelect" update="completeFloor" listener="#{roomListCreateMB.updateFloors()}"/>
	        	</p:autoComplete> <br />
	        	
	        	<h:outputLabel value="Andar" />
	        	<p:autoComplete value="#{roomListCreateMB.floorSelected}" id="completeFloor" completeMethod="#{roomListCreateMB.completeFloor}" 
					var="floor" itemLabel="#{floor.department.name} - #{floor.name}" itemValue="#{floor}" forceSelection="true" 
					converter="#{floorConverter}" dropdown="true" size="70" required="true" requiredMessage="Selecione o andar">
					<p:ajax event="itemSelect" update="@form" listener="#{roomListCreateMB.updateRooms()}" />
	        	</p:autoComplete> <br />
        	</h:panelGrid>
        	<p:imageCropper image="#{roomListCreateMB.realPathToPhoto}" rendered="#{not (roomListCreateMB.floorSelected eq null)}" 
        		 id="photo" initialCoords="10,10,50,50" value="#{cropperBean.imageCropped}" required="true" requiredMessage="Obrigatório"
        		 >
        		
       		</p:imageCropper>
        	
        	<ui:repeat var="room" value="#{roomListCreateMB.rooms}">
        		<script type="text/javascript">
					setTimeout(function(){addBlackPanel('#{room.id}',#{room.left},#{room.top},#{room.width},#{room.height},'#{room.name}')},1000);
        		</script>
        	</ui:repeat>
        	<br />
        	<p:commandButton value="Adicionar Sala" rendered="#{not (roomListCreateMB.floorSelected eq null)}" id="btnAdd"
	        	oncomplete="dlgAdd.show();" update=":formDialog" actionListener="#{roomListCreateMB.prepareRoom()}"
	        />	        
	        	
       		<p:dataTable value="#{roomListCreateMB.rooms}" var="room" emptyMessage="Não existem salas" filteredValue="#{roomListCreateMB.roomsFiltered}"
        		id="table" style="margin-top: 100px;">
        		<f:facet name="header">Tabela de salas cadastradas</f:facet>
        		<p:column headerText="Nome da sala" filterMatchMode="contains" filterBy="#{room.name}" sortBy="#{room.name}" filterStyle="width: 300px;"
        			width="500">
        			<h:outputLabel value="#{room.name}" />	
        		</p:column>
        		<p:column headerText="Deletar" width="100">
        			<p:commandButton icon="ui-icon-trash" update="table" actionListener="#{roomListCreateMB.deleteFloor(room)}" immediate="true"/>
        		</p:column>
        	</p:dataTable>
		</div>
	
</h:form>

<p:dialog modal="true" closable="true" draggable="true" resizable="true" header="Adicionar sala" id="dialogAdd" widgetVar="dlgAdd" closeOnEscape="true"
	dynamic="true">
	<h:form id="formDialog">
		<center>
		<h:outputLabel value="Adicionando sala para o andar [#{roomListCreateMB.floorSelected.name}] do departamento [#{roomListCreateMB.departmentSelected.name}] - #{roomListCreateMB.departmentSelected.institution.name}" />
		<h:panelGrid columns="3">
			<h:outputLabel value="Nome da sala" />
			<p:inputText value="#{roomListCreateMB.room.name}" id="txtRoomName" required="true"
				requiredMessage="Obrigatório nome da sala" size="50" widgetVar="txtRoomName" />
			<p:message for="txtRoomName"/>
		</h:panelGrid>
		<p:commandButton value="Cadastrar" actionListener="#{roomListCreateMB.addRoom()}" oncomplete="dlgAdd.hide();" update=":form:table :form:growl"
			onsuccess="addBlackPanelOnSubmit();"/>
		<p:commandButton value="Cancelar" type="button" onclick="dlgAdd.hide();"/>
		</center>
	
	</h:form>

</p:dialog>
    </ui:define>
    <ui:define name="moreScripts">
    	<script
			src="#{facesContext.externalContext.request.contextPath}/resources/js/cropper.js"
			type="text/javascript" charset="utf-8" />
    </ui:define>
    
</ui:composition>