Server/ClassroomEvents/src/main/java/br/ufscar/dc/gsdr/ClassroomEvents/model/Agent.java
package br.ufscar.dc.gsdr.ClassroomEvents.model;

import java.nio.charset.Charset;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;

import org.bouncycastle.util.encoders.Hex;
import org.codehaus.jackson.annotate.JsonIgnore;

import br.ufscar.dc.gsdr.ClassroomEvents.enumeration.Entities;

@Entity
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="user_type",discriminatorType=DiscriminatorType.INTEGER)
public abstract class Agent {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@Column
	private String fullname;
	
	@Column
	private String username;
	
	@Column
	@JsonIgnore
	private String password;
	
	@Column
	@JsonIgnore
	private String token;
	
	@Column
	@JsonIgnore
	private Date tokenTTL;
	
	public Agent(){
		
	}
	
	public boolean isAdmin(){
		if (this instanceof Admin)
			return true;
		else
			return false;
	}
	
	public boolean isSecretary(){
		if (this instanceof Secretary)
			return true;
		else
			return false;
	}
	
	public boolean isTeacher(){
		if (this instanceof Teacher)
			return true;
		else
			return false;
	}
	
	public String getPresentableInstanceName(){
		if(this instanceof Admin){
			return "Admin";
		}else{
			if(this instanceof Student){
				return "Estudante";
			}else{
				if(this instanceof Teacher){
					return "Professor";
				}else{
					if(this instanceof Secretary){
						return "Secretário";
					}else{
						return "";
					}
				}
			}
		}
	}
	
	public static Agent instantiateNew(Entities entity){
		switch (entity) {
		case ADMIN:
			return new Admin();
		case SECRETARY:
			return new Secretary();
		case STUDENT:
			return new Student();
		case TEACHER:
			return new Teacher();
		default:
			return null;
		}
	}
	
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Agent other = (Agent) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	public String getFullname() {
		return fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Long getId() {
		return id;
	}
	
	public static String hashPassword(String password){
		try {
			MessageDigest messageDigest = MessageDigest.getInstance("MD5");
			messageDigest.reset();
			messageDigest.update(password.getBytes(Charset.forName("UTF8")));
			return new String(Hex.encode(messageDigest.digest()));
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		} catch(NullPointerException npe){
			
		}
		return "";
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getTokenTTL() {
		return tokenTTL;
	}

	public void setTokenTTL(Date tokenTTL) {
		this.tokenTTL = tokenTTL;
	}
	
	
	
//	public static void main(String[] args) {
//		System.out.println("molina" + hashPassword("molina"));
//	}
	
	
}

Server/ClassroomEvents/src/main/webapp/management/user/create.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    template="/WEB-INF/templates/system.xhtml">
    <ui:define name="content">
<h:form id="form">
	<p:growl id="growl"/>
    	<div style="text-align:center;">
        	<h1>Criação de Usuário</h1>
		</div>
		<p:fieldset legend="Dados">
			<h:panelGrid columns="3">
			
				<h:outputLabel value="Entidade*" />
				<p:selectOneButton value="#{userCreateMB.entityChoosen}" id="cmbEntity">
					<f:selectItems value="#{userCreateMB.entitiesTypes}" var="ent" itemLabel="#{ent.toStringSpecialPortuguese()}" itemValue="#{ent}"/>
					<p:ajax event="change" listener="#{userCreateMB.instantiateNewAgent()}"/>
				</p:selectOneButton>
				<p:message for="cmbEntity"/>
			
				<h:outputLabel value="Nome completo*" />
				<p:inputText value="#{userCreateMB.agent.fullname}" id="txtName" required="true"
					requiredMessage="Obrigatório nome do usuário" size="50"/>
				<p:message for="txtName" showSummary="true" showDetail="false"/>
				
				<h:outputLabel value="Username*" />
				<p:inputText value="#{userCreateMB.agent.username}" id="txtUser" required="true"
					requiredMessage="Obrigatório o username" validator="#{uniqueUsernameValidator.validate}"
					size="30">
					<p:ajax event="blur" process="txtUser" update="msgUsername" />	
				</p:inputText>
				<p:message for="txtUser" id="msgUsername" showSummary="true" showDetail="false"/>
				
				<h:outputLabel value="Senha*" />
				<h:inputSecret value="#{userCreateMB.password}" id="txtPassword" required="true"
					requiredMessage="Obrigatório a senha">	
				</h:inputSecret>
				<p:message for="txtPassword" id="msgPassword" showSummary="true" showDetail="false"/>
				
				<h:outputLabel value="Confirmação de senha*" />
				<h:inputSecret value="#{userCreateMB.confirmPassword}" id="txtConfirmPassword" required="true"
					requiredMessage="Obrigatório a confirmação da senha">	
				</h:inputSecret>
				<p:message for="txtConfirmPassword" id="msgConfirmPassword" showSummary="true" showDetail="false"/>
				
			</h:panelGrid>
		</p:fieldset>
		
		<div style="text-align:center; margin-top: 20px">
			<p:commandButton value="Cadastrar" update="@form" id="btnSave" action="#{userCreateMB.save()}"/>
		</div>
</h:form>
    </ui:define>
</ui:composition>

Server/ClassroomEvents/src/main/webapp/management/user/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    template="/WEB-INF/templates/system.xhtml">
    <ui:define name="content">
<h:form id="form">
		<p:commandButton immediate="true" ajax="false" action="userCreate" value="Cadastrar novo" rendered="#{loginMB.agentLogged.isAdmin()}"/>
    	<div style="text-align:center;">
        	<h1>Listagem de Usuários</h1>
        	
        	<p:dataTable value="#{userListMB.agents}" var="agent" emptyMessage="Não existem usuários" filteredValue="#{userListMB.filteredAgents}">
        		<p:column headerText="Username" filterMatchMode="contains" filterBy="#{agent.username}" sortBy="#{agent.username}">
        			<h:outputLabel value="#{agent.username}" />	
        		</p:column>
        		
        		<p:column headerText="Nome" filterMatchMode="contains" filterBy="#{agent.fullname}" sortBy="#{agent.fullname}">
        			<h:outputLabel value="#{agent.fullname}" />	
        		</p:column>
        		
        		<p:column headerText="Tipo" filterMatchMode="contains" filterBy="#{agent.presentableInstanceName}" sortBy="#{agent.presentableInstanceName}">
        			<h:outputLabel value="#{agent.presentableInstanceName}" />	
        		</p:column>
        		
        	
        	
        	</p:dataTable>
		</div>
	
</h:form>
    </ui:define>
</ui:composition>