Server/ClassroomEvents/src/main/java/br/ufscar/dc/gsdr/ClassroomEvents/model/Reserve.java
package br.ufscar.dc.gsdr.ClassroomEvents.model;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
@Entity
public class Reserve {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@Column
	private Long beginMillis;
	
	@Column
	private Long endMillis;
	
	@Column
	private String teacherName;
	
	@Column
	private Date requestedIn;
	
	@Column
	private Boolean reserveGranted;
	
	@Column
	private Long userReserved;
	
	@ManyToOne
	private Room room;
	
	@ManyToOne
	private Teacher teacher;
	
	public Reserve(){
		
	}
	
	public String getTeacherNameProccessed(){
		if(teacher != null)
			return teacher.getFullname();
		else
			return teacherName;
	}
	
	
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Reserve other = (Reserve) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
	public String reserveGrantedAsString(){
		if(reserveGranted != null){
			if(reserveGranted)
				return "Sim";
			else
				return "Não";
		}else{
			return "Não decidido";
		}
	}
	
	public Date getBeginMillisAsDate(){
		return new Date(beginMillis);
	}
	
	public Date getEndMillisAsDate(){
		return new Date(endMillis);
	}

	public Long getBeginMillis() {
		return beginMillis;
	}

	public void setBeginMillis(Long beginMillis) {
		this.beginMillis = beginMillis;
	}

	public Long getEndMillis() {
		return endMillis;
	}

	public void setEndMillis(Long endMillis) {
		this.endMillis = endMillis;
	}

	public String getTeacherName() {
		return teacherName;
	}
	public void setTeacherName(String teacherName) {
		this.teacherName = teacherName;
	}
	public Date getRequestedIn() {
		return requestedIn;
	}
	public void setRequestedIn(Date requestedIn) {
		this.requestedIn = requestedIn;
	}
	public Boolean getReserveGranted() {
		return reserveGranted;
	}
	public void setReserveGranted(Boolean reserveGranted) {
		this.reserveGranted = reserveGranted;
	}
	public Room getRoom() {
		return room;
	}
	public void setRoom(Room room) {
		this.room = room;
	}
	public Long getId() {
		return id;
	}
	public Teacher getTeacher() {
		return teacher;
	}
	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Long getUserReserved() {
		return userReserved;
	}

	public void setUserReserved(Long userReserved) {
		this.userReserved = userReserved;
	}
	
	
	
	
	
	
}

Server/ClassroomEvents/src/main/webapp/management/reserve/create.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    template="/WEB-INF/templates/system.xhtml">
    <ui:define name="content">
<h:form id="form">
    	<div style="text-align:center;">
        	<h1>Registro de reserva</h1>
		</div>
		<p:growl id="growl"/>
		<p:fieldset legend="Dados">
			<h:panelGrid columns="3" id="grid">
				<h:outputLabel value="Sala" />
				<p:autoComplete value="#{reserveCreateMB.reserve.room}" id="completeRoom" completeMethod="#{reserveCreateMB.completeRoom}" 
					var="r" itemLabel="[#{r.floor.department.institution.name}] [#{r.floor.department.name}] [#{r.floor.name}] [#{r.name}]" itemValue="#{r}" forceSelection="true" 
					converter="#{roomConverter}" dropdown="true" size="90" required="true" requiredMessage="Selecione a sala" minQueryLength="2" queryDelay="600">
				</p:autoComplete>
				<p:message for="completeRoom" />
			
			
				<h:outputLabel value="Começa" />
				<p:calendar id="calBegin" value="#{reserveCreateMB.begin}"
					pattern="dd/MM/yyyy HH:mm:ss" locale="pt" effect="slideDown" navigator="true" 
					converterMessage="Não foi possível entender a data" yearRange="c+0:c+1" showOn="button"
					style="text-align:center;" required="true" requiredMessage="Obrigatório">
				</p:calendar>
				<p:message for="calBegin"/>
				
				<h:outputLabel value="Termina" />
				<p:calendar id="calEnd" value="#{reserveCreateMB.end}"
					pattern="dd/MM/yyyy HH:mm:ss" locale="pt" effect="slideDown" navigator="true" 
					converterMessage="Não foi possível entender a data" yearRange="c+0:c+1" showOn="button"
					style="text-align:center;" required="true" requiredMessage="Obrigatório">
				</p:calendar>
				<p:message for="calEnd"/>
			
				</h:panelGrid>
				<h:panelGrid columns="3" id="grid2">
				<h:outputLabel value="Professor cadastrado?" />
				<p:selectBooleanCheckbox value="#{reserveCreateMB.specificTeacher}" id="cbSpecific">
					<p:ajax update="grid2" listener="#{reserveCreateMB.defineChooseSpecific()}"/>
				</p:selectBooleanCheckbox>
				<br />
				
				<h:outputLabel value="Professor cadastrado" rendered="#{reserveCreateMB.specificTeacher}" id="lblProfCad"/>
				<p:autoComplete value="#{reserveCreateMB.reserve.teacher}" id="completeTeacher" completeMethod="#{reserveCreateMB.completeTeacher}" 
					var="t" itemLabel="#{t.fullname}" itemValue="#{t}" forceSelection="true" 
					converter="#{teacherConverter}" dropdown="true" size="70" required="true" requiredMessage="Selecione o professor"
					rendered="#{reserveCreateMB.specificTeacher}">
				</p:autoComplete>
				<p:message for="completeTeacher" rendered="#{reserveCreateMB.specificTeacher}"/>
				
				<h:outputLabel value="Professor não cadastrado" rendered="#{not reserveCreateMB.specificTeacher}"/>
				<p:inputText value="#{reserveCreateMB.reserve.teacherName}" required="true" requiredMessage="Obrigatório"
					id="txtTeacher" rendered="#{not reserveCreateMB.specificTeacher}" size="70"/>
				<p:message for="txtTeacher" rendered="#{not reserveCreateMB.specificTeacher}"/>
				
			
			</h:panelGrid>
		</p:fieldset>
		
		
		<div style="text-align:center; margin-top: 20px">
			<p:commandButton value="Cadastrar" update="@form" id="btnSave" action="#{reserveCreateMB.save()}"/>
		</div>
</h:form>
    </ui:define>
    
    <ui:define name="moreScripts">
        <script
	src="#{facesContext.externalContext.request.contextPath}/resources/js/locale-primefaces.js"
	type="text/javascript" charset="utf-8" />
    </ui:define>
</ui:composition>

Server/ClassroomEvents/src/main/webapp/management/reserve/list.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    template="/WEB-INF/templates/system.xhtml">
    <ui:define name="content">
<h:form id="form">
		<p:commandButton immediate="true" ajax="false" action="reserveCreate" value="Cadastrar nova"/>
    	<div style="text-align:center;">
        	<h1>Reservas</h1>
        	<!-- Admin's view -->
        	<p:growl id="growl"/>
        	<p:panel id="pnlAdmin" rendered="#{loginMB.agentLogged.isAdmin() or loginMB.agentLogged.isSecretary()}" style="border: 0px !important;">
       			<p:dataTable value="#{reserveListMB.reservesPendent}" emptyMessage="Não existem reservas pendentes" rows="10" var="reserve" 
       				id="tablePendent">
       				<f:facet name="header">Pendentes</f:facet>
       			
       				<p:column headerText="Sala" width="500">
       					<h:outputLabel value="[#{reserve.room.floor.department.institution.name}] [#{reserve.room.floor.department.name}] [#{reserve.room.floor.name}] #{reserve.room.name}" />	
       				</p:column>
       				
       				<p:column headerText="Solicitada em" width="200">
						<h:outputLabel value="#{reserve.requestedIn}" >
							<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
						</h:outputLabel>
					</p:column>
					
					<p:column headerText="Horário:" width="200">
						<h:outputLabel value="#{reserve.beginMillisAsDate}" >
							<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
						</h:outputLabel>
						<h:outputLabel value="até" />
						<h:outputLabel value="#{reserve.endMillisAsDate}" >
							<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
						</h:outputLabel>
					</p:column>
					
					
       				
					<p:column headerText="Professor" width="300">
						<h:outputLabel value="#{reserve.teacherNameProccessed}" />
					</p:column>        			
					
					<p:column headerText="Ações" width="300">
						<p:commandButton icon="ui-icon-search" actionListener="#{reserveListMB.prepareReservePendent(reserve)}" onsuccess="dlgDetails.show();"
							update=":formDetails"/>
						<p:commandButton icon="ui-icon-check" actionListener="#{reserveListMB.grantReservePendent(reserve)}" update="@form"/>
						<p:commandButton icon="ui-icon-closethick" actionListener="#{reserveListMB.denyReservePendent(reserve)}" update="@form"/>
					</p:column>
       			
       			</p:dataTable>
       			
       			<p:dataTable value="#{reserveListMB.reservesHistorical}" emptyMessage="Não existem reservas no seu histórico" rows="10" var="reserve"
       				style="margin-top : 100px;" id="tableHistorical">
       				<f:facet name="header">Respondidas</f:facet>
       				<p:column headerText="Sala" width="500">
       					<h:outputLabel value="[#{reserve.room.floor.department.institution.name}] [#{reserve.room.floor.department.name}] [#{reserve.room.floor.name}] #{reserve.room.name}" />	
       				</p:column>
       				
       				<p:column headerText="Solicitada em" width="200">
						<h:outputLabel value="#{reserve.requestedIn}" >
							<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
						</h:outputLabel>
					</p:column>
					
					<p:column headerText="Horário:" width="300">
						<h:outputLabel value="#{reserve.beginMillisAsDate}" >
							<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
						</h:outputLabel>
						<h:outputLabel value="até" />
						<h:outputLabel value="#{reserve.endMillisAsDate}" >
							<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
						</h:outputLabel>
					</p:column>
       				
					<p:column headerText="Professor" width="300">
						<h:outputLabel value="#{reserve.teacherNameProccessed}" />
					</p:column>        			
					
					<p:column headerText="Concedida" width="80">
						<h:outputLabel value="#{reserve.reserveGranted ? 'Sim' : 'Não'}" />
					</p:column>
					
					<p:column headerText="Ações" width="300">
						<p:commandButton icon="ui-icon-search" actionListener="#{reserveListMB.prepareReserveHistorical(reserve)}" onsuccess="dlgDetails.show();"
							update=":formDetails"/>
						<p:commandButton icon="ui-icon-help" update="@form" actionListener="#{reserveListMB.markPendent(reserve)}"/>
						<p:commandButton icon="ui-icon-check" rendered="#{(not reserve.reserveGranted)}" actionListener="#{reserveListMB.grantReserveHistorical(reserve)}"
							update="tableHistorical :form:growl"/>
						<p:commandButton icon="ui-icon-closethick" rendered="#{reserve.reserveGranted}" actionListener="#{reserveListMB.denyReserveHistorical(reserve)}"
							update="tableHistorical :form:growl"/>
					</p:column>
       			</p:dataTable>
        			
			</p:panel>
        	
        	<!-- Teacher's view -->
        	<p:layout id="pnlTeacher" rendered="#{loginMB.agentLogged.isTeacher()}" style="border: 0px !important;">
        		<p:layoutUnit position="center" style="border: 0px !important;">
        			<h:outputLabel value="Ainda não implementado. Use o aplicativo do celular" />	
        		</p:layoutUnit>
        	</p:layout>
    
    	<p:commandButton icon="ui-icon-search" value="Visualizar" type="button" style="margin-top: 30px;"/>
		<p:commandButton icon="ui-icon-help" value="Marcar como pendente" type="button"/>
		<p:commandButton icon="ui-icon-check" value="Concender reserva" type="button"/>
		<p:commandButton icon="ui-icon-closethick" value="Negar reserva" type="button"/>    	
		</div>
	
</h:form>

<p:dialog modal="true" closable="true" resizable="false" draggable="true" maximizable="true" minimizable="true" id="dialogDetails" widgetVar="dlgDetails">
	<h:form id="formDetails">
		<h:panelGrid columns="2">
			<h:outputLabel value="Sala:" style="font-weight: bold" />
			<h:outputLabel value="#{reserveListMB.reserve.room.floor.department.institution.name}] [#{reserveListMB.reserve.room.floor.department.name}] [#{reserveListMB.reserve.room.floor.name}] #{reserveListMB.reserve.room.name}" />
			
			<h:outputLabel value="Requisitado em: " style="font-weight: bold" />
			<h:outputLabel value="#{reserveListMB.reserve.requestedIn}" >
				<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
			</h:outputLabel>
			
			<h:outputLabel value="Professor: " style="font-weight: bold" />
			<h:outputLabel value="#{reserveListMB.reserve.teacherNameProccessed}" />
			
			<h:outputLabel value="Começo: " style="font-weight: bold" />
			<h:outputLabel value="#{reserveListMB.reserve.beginMillisAsDate}" >
				<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
			</h:outputLabel>
			
			<h:outputLabel value="Fim: " style="font-weight: bold" />
			<h:outputLabel value="#{reserveListMB.reserve.endMillisAsDate}" >
				<f:convertDateTime pattern="dd/MM/yy HH:mm"/>
			</h:outputLabel>
			
			<h:outputLabel value="Concedida:" style="font-weight: bold" />
			<h:outputLabel value="#{reserveListMB.reserve.reserveGrantedAsString()}" />
			
		</h:panelGrid>
		<div style="text-align:center; margin-top: 50px;">
			<p:commandButton value="Fechar" type="button" onclick="dlgDetails.hide();"/>
		</div>
	</h:form>

</p:dialog>

    </ui:define>
</ui:composition>